import json

stories_text = """
### 1. The Brahmin's Gift
Once, there lived a pious Brahmin in a village who used to perform religious rituals. On one occasion, he was rewarded with a cow by a rich man for his service. As the Brahmin started to bring the cow home, three rogues saw him. Being lazy, they wanted to cheat the Brahmin out of his cow and quickly hatched a plan. The first rogue approached the Brahmin and said, "Are you a washerman that you're pulling a donkey?" The Brahmin was annoyed at being mistaken for a washerman and kept walking. A little later, he was met by the second rogue, who asked him why a Brahmin like him needed to pull a pig. Now confused, the Brahmin pressed on. Some distance later, the third rogue met him and asked why he was pulling a wild animal. Totally confused and terrified, the Brahmin thought the animal was a shape-shifting devil. He ran away, leaving the cow behind. The three tricksters laughed at how easily they had cheated him.
> **Story Moral:** Believe your own eyes rather than what you hear.
> ### 2. The Foolish Lion and the Clever Rabbit
Long ago, a ferocious, greedy lion lived in the forest and started killing all the animals. Seeing this, the animals gathered and approached the lion with an offer: one animal from each species would volunteer to be eaten by him every day. Eventually, it was the rabbits' turn, and they chose a wise old rabbit. The rabbit intentionally took his sweet time reaching the lion. Getting impatient, the lion swore to kill all the animals the next day, but the rabbit finally arrived at sunset. When the enraged lion demanded answers, the calm rabbit explained that it wasn't his fault. He claimed that a group of rabbits had been on their way, but another angry lion attacked them and ate all of them except him. The rabbit added that this other lion was actively challenging the king's supremacy. Enraged, the lion demanded to be taken to his rival. The wise rabbit led him to a deep well filled with water and showed him his own reflection. The furious lion began growling, and seeing his angry reflection growl back, he jumped into the water to attack. He drowned, and the wise rabbit saved the forest.
> **Story Moral:** Intelligence wins over might.
> ### 3. The Fox Reared by the Lion
A lion and a lioness lived in a dense forest and in due course gave birth to two cubs. The lion asked the lioness to stay home with the cubs while he hunted. One day, unable to find any large prey, the lion brought home a helpless little fox as a gift. The lioness raised the fox kit with the exact same love as her own cubs, and the three young animals grew up playing together. One day, the young animals encountered an elephant. The lion cubs immediately wanted to fight it, but the frightened fox kid urged them to run away. They all fled back to their mother, and the lion cubs mockingly told her what happened. When the lioness laughed, the fox kid took offense and angrily challenged her for calling him a coward. The lioness replied honestly, "What's wrong with eating an elephant? You feel like that only because you're not a lion. You are the child of a fox, and your breed never eats elephants. If you cannot be bold, please leave us and live with your own tribe." Realizing the truth, the fox kid left for the forest.
> **Story Moral:** A coward will always remain a coward, even in the company of the brave.
> ### 4. The Monkey and the Crocodile
Long ago, a monkey named Red-face lived on a sweet apple tree by the seaside. One day, a crocodile named Ugly-mug swam ashore. Red-face threw nectar-like apples to him, and they soon became fast friends, with Ugly-mug returning every day. Ugly-mug also began taking some apples home to his wife. His greedy wife asked where he got such delicious fruit, and upon hearing about the monkey, she demanded to eat the monkey's heart. She reasoned that someone who ate such sweet fruit must have a heart filled with pure nectar. Ugly-mug was angry and refused to deceive his friend, but his wife declared a hunger strike until he complied. Desperate, Ugly-mug invited Red-face to his house for supper, claiming his wife was thrilled to host him. The monkey accepted but wondered how he would cross the sea. Ugly-mug offered to carry him on his back. In the middle of the deep ocean, the guilty crocodile confessed his wife's plan. Thinking quickly, Red-face said, "Oh dear! Why didn't you tell me earlier? I leave my heart safely stored back on the tree. Let us swim back so I can fetch it for your wife." The foolish crocodile turned back, and the moment they reached the shore, the terrified monkey scrambled up the tree, never to return. He scolded the crocodile for betraying their friendship. Ashamed, Ugly-mug asked how he could make amends, especially since a huge rival crocodile had now occupied his home. The monkey advised him to fight the intruder to win back his home and his wife's respect. The crocodile followed the advice and lived happily once more.
> **Story Moral:** Intelligence wins over might.
> ### 5. The Moon Lake
A large herd of elephants lived happily under the care of a majestic king until a severe drought hit the jungle. To save them from dying of thirst, the king sent elephants in all directions to find water. One elephant discovered a massive lake in a distant jungle, and the king ordered the herd to march there. Unfortunately, right next to the beautiful lake was a colony of rabbits. As the heavy elephants marched through, thousands of rabbits were trampled to death or severely injured. In a panic, the rabbit king called an urgent meeting. A brave little rabbit stood up and volunteered to go as a messenger to the elephant king. Finding the elephant king surrounded by his herd, the rabbit wisely climbed a huge rock to avoid being crushed and shouted, "O King of elephants, hear me! I am a messenger from the mighty Moon." He warned the king, "The Moon says you have soiled his holy lake and killed his protected rabbits. If you do not stop, something terrible will happen to your herd." Shocked and deeply superstitious, the elephant king asked how to beg for forgiveness. The rabbit led the king alone to the edge of the lake at night and showed him the Moon's reflection in the still water. When the elephant dipped his trunk into the water to bow in worship, the ripples made the reflection dance. "Look! The Moon is angrier than ever because you touched his holy waters," whispered the rabbit. The terrified elephant king bowed his head, promised never to return or harm the rabbits again, and led his herd away forever.
> **Story Moral:** Intelligence wins over might.
> ### 6. The Sparrow and the Elephant
A sparrow couple lived happily in a nest they built on a tree branch where they had laid their eggs. One morning, a wild elephant gripped by spring fever rampaged through the area and aggressively snapped the branch supporting the nest. The eggs were completely destroyed, leaving the mother sparrow heartbroken. Seeing her grief, her friend the woodpecker offered comfort and promised a plan to destroy the elephant. The woodpecker enlisted a black fly, who in turn brought in a counselor frog. Together, they devised a brilliant scheme. At noon, the black fly began buzzing sweet music directly into the elephant’s ears. Charmed, the elephant closed his eyes to listen. Instantly, the woodpecker flew down and pecked out the elephant's eyes, blinding him. Thirsty and in pain, the elephant stumbled through the forest searching for water. The frog sat at the edge of a massive, deep pit and croaked loudly. Misled into thinking the croaking meant a fresh pond was nearby, the elephant charged forward, tumbled into the pit, and died.
> **Story Moral:** Collective wit and teamwork can overcome massive strength.
> ### 7. The Sage's Daughter
A childless sage lived with his wife on the banks of a river. One day, while the sage was praying in the water, an eagle flying overhead accidentally dropped a tiny female mouse right into his hands. He brought the mouse home, and he and his wife used his mystical powers to transform the creature into a human baby girl. They raised her as their own daughter, and she grew into a beautiful maiden. When she turned sixteen, the sage sought the most powerful groom in the universe for her and called upon the Sun God. However, the daughter rejected him, saying, "He is far too hot, and I will be reduced to ashes." The Sun God suggested the Lord of the Clouds, who can easily block the sun's rays. When the Cloud God appeared, the girl rejected him too, citing his dark appearance and terrifying thunder. The Cloud God suggested the Wind God, who easily blows clouds away. The girl rejected the Wind God because he was restless and always on the move. The Wind God pointed to the Mountain Lord, who stands rock-solid against the wind. Yet, the daughter rejected the mountain, calling him cold-hearted, and requested someone softer but stronger. Finally, the Mountain Lord suggested a mouse, as mice are soft yet easily chew holes straight through mountains. Hearing this, the daughter happily agreed. The sage smiled at the work of destiny, turned her back into a mouse, and happily wed her to her match.
> **Story Moral:** Destiny cannot be changed.
> ### 8. The Blue Jackal
A hungry jackal wandered into a city looking for food and ended up being chased by a pack of aggressive dogs. In his desperation to hide, he ducked into a dyer's house and fell directly into a large vat of indigo dye, staining his fur bright blue from head to toe. When he returned to the forest, the animals were terrified because they couldn't identify what kind of creature he was. Seising the opportunity, the jackal proclaimed, "I am a fierce creature sent directly by Indra, the King of Gods, to guard this forest!" The gullible animals believed him. The blue jackal established a grand court, appointing the lion as his prime minister, the tiger as his bedroom guardian, and the elephant as his doorkeeper. He promptly banished all other jackals from the forest so no one would recognize him. He lived a life of supreme luxury while the other animals hunted and brought him food. One evening, a pack of wild jackals passed nearby, howling loudly. Unable to suppress his natural instincts, the blue jackal joined in and howled at the top of his voice. Realizing they had been fooled by an ordinary jackal, the enraged animals killed him instantly.
> **Story Moral:** You cannot hide your true nature for long.
> ### 9. The Mongoose and the Farmer's Wife
A farmer and his wife had a newborn son. Wanting a companion and protector for the baby, they decided to adopt a young mongoose as a pet. A few months later, the couple needed to leave the house briefly. Believing the mongoose would watch over the baby, they left them alone together. The farmer's wife returned home first and was horrified to find the mongoose waiting at the door with its mouth heavily stained with fresh blood. Assuming the animal had killed her infant, she flew into a blind rage and threw a heavy box directly at the mongoose, severely injuring it. She rushed into the nursery, only to find her baby sleeping peacefully next to a dead, torn snake. Realizing the mongoose had actually saved her son's life, she ran outside, but it was too late—the loyal animal had died from the blow. She wept bitterly over her hasty actions.
> **Story Moral:** Do not act in haste; think carefully before you strike.
> ### 10. The Greedy Jackal
A lazy jackal was wandering through the hills one day when he stumbled upon a grim scene: a dead hunter, a dead wild boar, and a bow lying on the ground. The hunter had shot the boar with an arrow, but the wounded boar had killed the hunter before collapsing and dying from its injuries. The jackal rejoiced at finding an enormous amount of food that would last him for weeks. However, his excessive greed got the better of him. He decided to preserve the meat and eat the tightly strung bowstring first. The moment he bit into the taut string, it snapped violently, causing the sharp wooden end of the bow to pierce right through his mouth, killing him instantly.
> **Story Moral:** Excessive greed always brings its own ruin.
> ### 11. The Daydreaming Priest
A deeply lazy and impoverished priest survived entirely by begging for alms, all while constantly dreaming of becoming incredibly wealthy. One morning, he received a generous pot of milk. He took it home, boiled it, drank a little, and added a small amount of curd to set the rest into curd overnight. As he lay down to sleep, his mind began to race with wild daydreams about the pot. He imagined: *"By morning, the milk will turn to curd. I will churn it into rich butter, heat it into ghee, and sell it at the market. With that money, I’ll buy a hen. The hen will lay eggs, leading to an entire poultry farm. Then I’ll trade the poultry for cows, open a massive dairy, and sell milk to the entire town. I’ll buy precious jewels, sell them to the king, and become so rich that I can marry a beautiful girl from a wealthy family. We will have a handsome son, and if he plays any mischief, I will get furious and beat him with a big stick like this!"* Lost entirely in his fantasy, his arm involuntarily grabbed a real stick resting next to his bed. He swung it hard, hitting the hanging pot. The pot shattered completely, spilling the milk everywhere and instantly waking him to reality.
> **Story Moral:** There is no substitute for hard work; dreams cannot be fulfilled without action.
> ### 12. The Heron and the Crab
An old, lazy heron lived near a pond and grew tired of fishing for his food. He devised a trick, standing by the water with a deeply sorrowful expression. A wise crab, who often helped the fish, noticed him and asked what was wrong. The heron sighed, "Alas! I overheard some fishermen saying they are going to cast nets and catch every single fish in this pond. I am heartbroken. However, I know of a beautiful, hidden lake far away where you would all be perfectly safe. If the fish want, I can carry a few of them in my beak every day to relocate them." Terrified, the fish eagerly volunteered. Every day, the heron loaded a few fish into his beak, flew over to a large flat rock, ate them, and left their bones scattered across the stone. Eventually, the crab asked for a turn to be relocated. As they flew near the rock, the crab looked down and saw the massive pile of fish bones. Realizing the heron’s deadly trap, the crab quickly clamped his sharp claws tightly around the heron's neck and snapped his head clean off. The crab crawled back to the pond and exposed the heron's lies to the remaining fish.
> **Story Moral:** Greed and deceit ultimately destroy the perpetrator.
> ### 13. The Crows and the Serpent
A crow couple built a beautiful nest at the top of a tree, but a wicked black serpent lived in a hollow burrow at the bottom of the same tree. Every time the female crow laid eggs, the serpent crawled up the trunk and ate them, leaving the couple heartbroken. Desperate for a solution, the crows approached their clever friend, the jackal, for advice. The jackal instructed them, "Go to the royal palace, steal a highly valuable item belonging to the queen, and drop it directly into the snake's burrow." The crow flew to the palace gardens and snatched a costly necklace while the queen was bathing. The royal guards immediately chased the bird. The crow flew back to the tree and dropped the glittering necklace straight into the serpent’s burrow right in front of the guards. When the guards dug into the burrow to retrieve the treasure, the serpent emerged hissed aggressively. The guards killed the snake on the spot, recovered the necklace, and left the crow family to live in peace.
> **Story Moral:** Intelligence wins over might.
> ### 14. The Gold-Giving Serpent
A poor Brahmin worked tirelessly on his fields, but his crops never yielded any profit. One hot afternoon, he noticed a large anthill on his land and saw a majestic serpent emerging from it. Thinking he had neglected the guardian deity of his land, he brought a plate of milk and offered it to the anthill. The next morning, when he went to retrieve the plate, he was astonished to find a bright gold coin resting on it. From that day on, the Brahmin offered milk daily and received a gold coin every morning. One day, the Brahmin had to travel to the city, so he instructed his son to feed the serpent. The greedy son thought, *"This anthill must be completely filled with thousands of gold coins! Why should I wait every day?"* He took a heavy stick and struck the serpent on the head. The injured snake survived the blow, bit the boy in self-defense, and the boy died instantly.
> **Story Moral:** Excess greed only leads to total loss.
> ### 15. The Swan and the Owl
A elegant swan spent his days playing around a beautiful lake. One day, an owl visited him, flattered him with praises, and requested to be his friend. The swan agreed, and they spent many happy days together by the lakeside. Soon, the owl grew bored of the lake and said, "I am returning to my home in the Lotus Wood. If you ever wish to visit me, come find me there." Eventually, the swan traveled to the Lotus Wood, but because it was daytime, the owl was hiding inside a dark tree hollow. The owl called out, telling the swan to rest until the sun set, as he could only come out at night. The next morning, while the swan was resting on a branch, a caravan of merchants passed through the woods. The merchants began chanting hymns, and the owl inside the tree gave a loud, ill-timed hoot. Believing the hooting was a terrible omen, one of the merchants drew an arrow to shoot down the bird. Sensing danger, the owl quickly retreated deeper into his hole, but the innocent swan didn't move in time. The arrow struck the swan, killing him.
> **Story Moral:** True friendship should be formed between equals who share the same lifestyle.
> ### 16. The Cat, the Partridge, and the Hare
A partridge lived comfortably in a dwelling at the foot of a tree. One day, it traveled to distant fields to feast on crops and stayed away for several weeks. In its absence, a hare stumbled upon the empty spot and moved in. When the plump partridge finally returned, it demanded its home back. A fierce argument ensued, with the hare arguing that property belongs to whoever currently occupies it, while the partridge claimed ancestral ownership. They decided to find a mediator and approached a cat living nearby who was known for posing as a deeply religious ascetic. Seeing them approach from a distance, the hypocritical cat put on a holy act and whispered weakly, "Alas, old age has made me partially deaf. Step closer, dear friends, and speak directly into my ear so I can judge your case fairly." Foolish and trusting, both the hare and the partridge stepped right up to the cat's face. The moment they were within reach, the cat struck, killed them both, and turned them into his meal.
> **Story Moral:** When two people fight blindly, an unscrupulous mediator walks away with the prize.
> ### 17. The Geese and the Tortoise
A pair of geese and a tortoise were inseparable friends who lived by a beautiful lake. A severe drought struck the region, and their lake began drying up rapidly. The geese decided they must fly to a distant, water-filled lake, but the tortoise couldn't fly. The geese came up with a creative plan: "We will hold a strong stick on either end with our beaks, and you must grip the center of the stick tightly with your mouth. However, you must promise to keep your mouth completely shut, no matter what, or you will fall to your death." The tortoise agreed. As they flew over a town, the townsfolk looked up, laughed, and cheered at the sight of geese carrying a tortoise. Unable to control his anger and anxiety, the tortoise opened his mouth to shout, "What are they laughing about?!" The moment he let go of the stick, he plummeted to the ground and died.
> **Story Moral:** Always listen to wise counsel and know when to stay silent.
> ### 18. The Bird with the Two Necks
Long ago, there lived a strange, mythical bird that possessed two distinct necks and heads but shared one single stomach. One day, the first head discovered a jar of delicious, sweet nectar and began drinking it happily. The second head watched longingly and begged, "Please let me taste a few drops of that nectar as well." The first head selfishly refused, saying, "Why does it matter? It all goes down into our common stomach anyway." Deeply insulted and furious, the second head began searching the forest floor. It soon discovered a jar of deadly poison and intentionally swallowed it down. The poison flowed directly into the shared stomach, and both heads perished together.
> **Story Moral:** A lack of sharing and cooperation within a single unit leads to mutual destruction.
> ### 19. The Three Fishes
Three large fishes who were close friends lived in a lake, but they possessed vastly different personalities. The first fish was a fatalist who believed everything was governed by destiny and couldn't be changed. The second fish was clever and highly resourceful, confident he could think his way out of any problem. The third fish was wise, preferring to think long and hard to avoid danger entirely. One evening, the wise fish overheard fishermen standing at the shore saying, "Look at those giant fish! This lake is packed with them. Let's return tomorrow morning with our nets." The wise fish hurried back to his friends and urged, "We must swim through the canal immediately and escape to the connected lake before morning." The clever fish scoffed, "I will stay; if they catch me, I’ll find a trick to escape." The fatalist fish sighed, "Whatever is meant to happen will happen. I was born here, and I won't leave." The wise fish didn't want to risk his life and swam through the canal alone that night. The next morning, the fishermen cast their nets and caught the remaining two friends. The clever fish immediately went completely limp, holding his breath to pretend he was dead. The fishermen carelessly threw him back into the water along with the day's debris, allowing him to escape. However, the fatalist fish kept thrashing wildly in the net, so the fishermen struck him down.
> **Story Moral:** Forethought and timely action are better than relying blindly on luck or reacting at the last minute.
"""

stories = []
import re

blocks = re.split(r'> ### \d+\.\s+', stories_text)
for block in blocks:
    if block.strip():
        # First one might start with ### \d+.
        if block.startswith("### "):
            match = re.match(r'### \d+\.\s+(.*?)\n(.*)', block, re.DOTALL)
            if match:
                title = match.group(1).strip()
                content = match.group(2).strip()
        else:
            lines = block.split('\n', 1)
            title = lines[0].strip()
            content = lines[1].strip() if len(lines) > 1 else ""

        moral_match = re.search(r'> \*\*Story Moral:\*\* (.*)', content)
        moral = moral_match.group(1).strip() if moral_match else ""
        text = re.sub(r'> \*\*Story Moral:\*\* .*', '', content).strip()

        stories.append({
            "title": title,
            "text": text,
            "moral": moral
        })

print(json.dumps(stories, indent=2))
